spring.application.name: amanda-ia
server.port: ${PORT:8080}

springdoc.swagger-ui.path: /

cloudkafka.topic: 1xpbgxp5-yai
cloudkafka.brokers: tricycle-01.srvs.cloudkafka.com:9094,tricycle-02.srvs.cloudkafka.com:9094,tricycle-03.srvs.cloudkafka.com:9094
cloudkafka.username: 1xpbgxp5
cloudkafka.password: YBepu9SHThb2LE90mvnozsDCfnsmUXxq

spring:
  data:
    mongodb:
      uri: ${URL_DB:mongodb://localhost:27017/ml-db?retryWrites=true&w=majority}

application.service: urls-ln
application.version: @project.version@